<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Could not save all items' => 'No se pudo guardar todos los elementos',
    'Could not save all readings' => 'No se pudo guardar todos las lecturas',
    'Could not save row' => 'No se pudo guardar la fila',
    'Could not save the user' => 'No se pudo guardar el usuario',
    'Home' => 'Inicio',
    'Passwords don\'t match' => 'Las contraseñas no concuerdan',
    'This does not look like a valid date range' => 'Esto no parece un rango de fechas válido',
    'Users' => 'Usuarios',
    'New user' => 'Nuevo usuario',
    'Rows' => 'Filas',
    'No rows found' => 'No se encontró filas',
    'New row' => 'Nueva fila',
    'Export' => 'Exportar',
    'Date range' => 'Rango de fechas',
    'Audit trail info' => 'Auditoría',
    'Cancel' => 'Cancelar',
    'Add table' => 'Añadir tabla',
    'Adding...' => 'Añadiendo...',
    'Adding row' => 'Añadiendo fila',
    'Updating row' => 'Actualizando fila',
    'Add row' => 'Añadir fila',
    'New row readings' => 'Lecturas de la nueva fila',
    'Table name' => 'Nombre de la tabla',
    'Created at' => 'Creado el',
    'Updated at' => 'Actualizado el',
    'by' => 'por',
    'Tables' => 'Tablas',
    'New table' => 'Nueva tabla',
    'Users' => 'Usuarios',
    'Logout' => 'Salir',
    'Name' => 'Nombre',
    'Login' => 'Ingresar',
    'Username' => 'Usuario',
    'Password' => 'Contraseña',
    'Add user' => 'Añadir usuario',
    'Update user' => 'Actualizar usuario',
    'Adding user...' => 'Añadiendo usuario...',
    'Updating user...' => 'Actualizando usuario...',
    'Is admin?' => '¿Es administrador?',
    'Repeat password' => 'Repetir contraseña',
    'Please fill out the following fields to login' => 'Por favor, rellene los siguientes campos para ingresar',
    'Are you sure you want to delete this table and all its readings?' => '¿Seguro que desea eliminar esta tabla y todas sus lecturas?',
    'Are you sure you want to delete this user?' => '¿Seguro que desea eliminar este usuario?',
    'Properties' => 'Propiedades',
    'Path' => 'Ruta',
    'Create child node' => 'Crear nodo hijo',
    'Create' => 'Crear',
    'Creating...' => 'Creando...',
    'View' => 'Ver',
    'Update' => 'Actualizar',
    'Save' => 'Guardar',
    'Delete' => 'Eliminar',
    'Tracking tables for performance statistical analysis.' => 'Tablas de seguimiento para análisis estadístico de rendimiento.',
    'The user cannot be deleted because is still referenced from rows he/she has created or updated' => 'El usuario no se puede borrar porque todavía es referenciado por filas que ha creado o actualizado'
];
